#!/bin/bash
#
#See skript kontrollib kas apache2 on installitud ja installib kui ei ole.
#
#
#
a2=$(dpkg-query -W -f='${status}' apache2 2>/dev/null | grep -c "ok installed")

if [ $a2 -eq 0 ]; then
echo "Installib apache2"
apt-get install -y apache2;
	elif [ $a2 -eq 1 ]; then
		echo "Apache2 on juba paigaldatud"
service apache2 status
fi
		
