#!/bin/bash
#
#See skript kontrollib kas apache2 on installitud ja installib kui ei ole.
#
#
#
a2=$(dpkg-query -W -f='${status}' apache2 2>/dev/null | grep -c "ok installed")
#kontrollib kas apache on juba installitud
if [ $a2 -eq 0 ]; then
#kui apache ei ole installitud võrdub $a2 nulliga kuna rida ei ole
echo "Installib apache2"
#ütleb kasutajale et apache2 installitakse
apt-get install -y apache2;
#installib apache2
	elif [ $a2 -eq 1 ]; then
#kui apache 2 on installitud võrdub $a2 ühega kuna otsing leiab rea
		echo "Apache2 on juba paigaldatud"
#ütleb kasutajale et apach2 on juba installitud
service apache2 status
#näitab kasutajale apache2 staatust
fi
#skripti lõpp
