#!/bin/bash
#
#
#
php=$(dpkg-query -W -f='${status}' php7.3 2>/dev/null | grep -c "ok installed")
if [ $php -eq 0 ]; then
	echo "PHP installitakse"
apt update
apt install php7.3
apt install php7.3-cli php7.3-common php7.3-curl php7.3-mbstring php7.3-mysql php7.3-xml
elif [ $php -eq 1 ]; then

	echo "PHP on olemas"
fi
