#!/bin/bash
#
#See skript installib wordpressi
#
a2=$(dpkg-query -W -f='${status}' apache2 2>/dev/null | grep -c "ok installed")
	if [ $a2 -eq 0 ]; then
		echo "Installib apache2"
		apt-get install -y apache2;
	elif [ $a2 -eq 1 ]; then
		echo "Apache2 on olemas"
php=$(dpkg-query -W -f='${status}' php7.3 2>/dev/null | grep -c "ok installed")
		if [ $php -eq 0 ]; then
		echo "PHP installitakse"
		apt update
		apt install php7.3
		apt install php7.3-cli php7.3-common php7.3-curl php7.3-mbstring php7.3-mysql php7.3-xml
	elif [ $php -eq 1 ]; then
		echo "PHP on olemas"
mysql=$(dpkg-query -W -f='${status}' mysql-server 2>/dev/null | grep -c "ok installed")
	if [ $mysql -eq 0 ]; then
		echo "Mysql installitakse"
		apt update
		apt install mysql-server
	elif [ $mysql -eq 1 ]; then
		echo "mysql on olemas"
myphp=$(dpkg-query -W -f='${status}' phpmyadmin 2>/dev/null | grep -c "ok installed")
	if [ $myphp -eq 0 ]; then
		echo "Myphpadmin installitakse"
		apt update
		apt install phpmyadmin php-mbstring php-gettext
           apt install phpmyadmin php-mbstring php-gettext
elif [ $myphp -eq 1 ]; then
		echo "myphpadmin on olemas"
wordpress=$(dpkg-query -W -f='${status}' wordpress 2>/dev/null | grep -c "ok installed")
        if [ $wordpress -eq -0 ]; then
		apt update
		apt install -y wordpress
	elif [ $wordpress -eq -1 ]; then
	echo "wordpress on olemas"
fi
fi
fi
fi
fi
